services:
  postgres:
    image: postgres:13
    container_name: marvel-postgres
    environment:
      POSTGRES_DB: marvel_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marvel-network

volumes:
  postgres_data:

networks:
  marvel-network:
    driver: bridge
